import {
  pgTable,
  pgEnum,
  text,
  uuid,
  timestamp,
  boolean,
  integer,
  jsonb,
  date,
  primaryKey,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import type { Questionnaire, QuestionnaireResponses } from "@quagga/types";

// Quagga Portal schema (AfrikaBurn Contributors App). FROZEN per
// docs/build-spec.md §Schema — feature agents do not add or alter tables.
// This file is the single hand-authored source of truth; everything under
// packages/db/migrations/ is generated by drizzle-kit and never hand-edited.
//
// Authentication/identity lives in Neon Auth (Better Auth). Our `users` table
// joins to it via `auth_user_id` (the upstream Better Auth user id).

// --- Enums ---------------------------------------------------------------
// Each tuple mirrors a Zod enum in @quagga/types (the validation authority);
// this is the storage authority. Keep the two in sync.

export const groupKindEnum = pgEnum("group_kind", [
  "org",
  "theme_camp",
  "artwork",
  "mutant_vehicle",
]);

export const joinabilityEnum = pgEnum("joinability", ["open", "invite_only"]);

// Reserved: visibility is currently DERIVED (registered ⇒ public). This column
// exists so explicit privacy settings can land later without a migration.
export const groupVisibilityEnum = pgEnum("group_visibility", [
  "default",
  "public",
  "members_only",
  "private",
]);

export const membershipRoleEnum = pgEnum("membership_role", [
  "god",
  "org_staff",
  "lead",
  "admin",
  "member",
]);

export const inviteKindEnum = pgEnum("invite_kind", [
  "member",
  "lead_transfer",
]);

export const registrationStatusEnum = pgEnum("registration_status", [
  "draft",
  "submitted",
  "under_review",
  "changes_requested",
  "approved",
  "rejected",
  "withdrawn",
]);

export const sectionKeyEnum = pgEnum("section_key", [
  "identity",
  "lnt",
  "participation",
  "size_logistics",
  "sound_placement",
  "suppliers_commerce",
]);

export const sectionReviewStatusEnum = pgEnum("section_review_status", [
  "open",
  "resolved",
]);

export const vettingStatusEnum = pgEnum("vetting_status", [
  "listed",
  "registered",
  "flagged",
]);

export const supplierSourceEnum = pgEnum("supplier_source", [
  "ab_sheet",
  "manual",
]);

export const paymentStatusEnum = pgEnum("payment_status", [
  "pending",
  "reconciled",
  "waived",
]);

// Questionnaire spine (ported 1:1 from Camp 404's pattern).
export const requiredActionTypeEnum = pgEnum("required_action_type", [
  "questionnaire",
  "acknowledgement",
  "payment",
  "profile_update",
]);

export const requiredActionStatusEnum = pgEnum("required_action_status", [
  "pending",
  "completed",
  "waived",
  "expired",
]);

export const questionnaireScopeEnum = pgEnum("questionnaire_scope", [
  "everyone",
  "individual",
  "opt_in",
]);

export const activationStatusEnum = pgEnum("activation_status", [
  "draft",
  "open",
  "closed",
]);

export const questionnaireStatusEnum = pgEnum("questionnaire_status", [
  "draft",
  "published",
  "unpublished",
]);

// --- Users ---------------------------------------------------------------
// Camp-specific identity join. Minimal by design: NO role columns — every role
// is a `memberships` row. Account persists; per-edition data hangs elsewhere.

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  authUserId: text("auth_user_id").notNull().unique(),
  email: text("email"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Editions ------------------------------------------------------------
// Years are the root namespace. Bios and registrations hang off an edition.
// Seed: AfrikaBurn 2027 (2027-04-26 → 2027-05-02, active).

export const editions = pgTable("editions", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  year: integer("year").notNull().unique(),
  startDate: date("start_date", { mode: "string" }).notNull(),
  endDate: date("end_date", { mode: "string" }).notNull(),
  isActive: boolean("is_active").notNull().default(false),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Burner bios ---------------------------------------------------------
// One row per user × edition (carried forward year to year by confirm-and-copy,
// wave 2+). Field set mirrored from Camp 404's burner profile. `privacy_flags`
// is a per-field public/private map; the HARD-LOCKED always-private fields
// (id_number, passport_number, phone, both emergency contacts, medical) can
// NEVER be set public — enforced in @quagga/core (privacy hard-lock). SA ID /
// passport are pgcrypto-encrypted (never stored plaintext); encryption happens
// in route handlers via @quagga/db/crypto. `attended_years` is the set of
// specific AfrikaBurn years attended (2007–2026, never 2020/2021).

export const burnerBios = pgTable(
  "burner_bios",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),

    // Public-toggleable identity fields.
    displayName: text("display_name"),
    legalName: text("legal_name"),
    homeCity: text("home_city"),
    bio: text("bio"),
    skills: jsonb("skills").$type<string[]>().notNull().default([]),
    // Specific AfrikaBurn years attended (2007–2026, never 2020/2021 — no burn).
    attendedYears: jsonb("attended_years")
      .$type<number[]>()
      .notNull()
      .default([]),
    firstTime: boolean("first_time").notNull().default(false),

    // Contact — `email` is display/contact; `phone` is HARD-LOCKED private
    // (stored E.164).
    contactEmail: text("contact_email"),
    phone: text("phone"),

    // HARD-LOCKED private. Two emergency contacts (on-site + off-site), each
    // split into name + phone (E.164). Stored plaintext, like the other
    // contact fields — only id/passport are pgcrypto-encrypted.
    onsiteContactName: text("onsite_contact_name"),
    onsiteContactPhone: text("onsite_contact_phone"),
    offsiteContactName: text("offsite_contact_name"),
    offsiteContactPhone: text("offsite_contact_phone"),
    medicalNotes: text("medical_notes"),

    // HARD-LOCKED private + pgcrypto-encrypted (base64 ciphertext columns).
    saIdEncrypted: text("sa_id_encrypted"),
    passportEncrypted: text("passport_encrypted"),

    // Per-field public/private map, e.g. { "displayName": true, "bio": true }.
    // Hard-locked fields are force-private regardless of what's stored here.
    privacyFlags: jsonb("privacy_flags")
      .$type<Record<string, boolean>>()
      .notNull()
      .default({}),

    // Questionnaire-engine bookkeeping (this is a "code questionnaire").
    version: text("version").notNull(),
    startedAt: timestamp("started_at", { mode: "date" }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { mode: "date" }),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (b) => ({
    userEditionIdx: uniqueIndex("burner_bios_user_edition_idx").on(
      b.userId,
      b.editionId,
    ),
    editionIdx: index("burner_bios_edition_idx").on(b.editionId),
  }),
);

// --- Profile keys --------------------------------------------------------
// Server-generated keypair at onboarding (reproducible; users never manage
// keys). Used for nothing yet except future QR attestations. The private key is
// stored encrypted; the public key is plaintext.

export const profileKeys = pgTable("profile_keys", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  publicKey: text("public_key").notNull(),
  encryptedPrivateKey: text("encrypted_private_key").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Groups --------------------------------------------------------------
// One joinable-group table. A PROJECT is any non-org group (the kind that
// registers and earns entitlements). Exactly one `org` row is seeded
// ("AfrikaBurn"). `name_normalized` is unique per kind (case/space/punct-
// insensitive; the normalizer lives in @quagga/core).

export const groups = pgTable(
  "groups",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    kind: groupKindEnum("kind").notNull(),
    name: text("name").notNull(),
    nameNormalized: text("name_normalized").notNull(),
    slug: text("slug").notNull(),
    // 60-word limit (for camps) enforced in @quagga/core + the UI.
    description: text("description"),
    joinability: joinabilityEnum("joinability")
      .notNull()
      .default("invite_only"),
    // Reserved column — see groupVisibilityEnum.
    visibility: groupVisibilityEnum("visibility").notNull().default("default"),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (g) => ({
    // Unique per kind, case/space/punct-insensitive (normalized upstream).
    kindNameUniq: uniqueIndex("groups_kind_name_normalized_idx").on(
      g.kind,
      g.nameNormalized,
    ),
    slugUniq: uniqueIndex("groups_slug_idx").on(g.slug),
  }),
);

// --- Memberships ---------------------------------------------------------
// user × group with a role. `god` is only valid on the org group (enforced in
// app logic). unique(user, group).

export const memberships = pgTable(
  "memberships",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    role: membershipRoleEnum("role").notNull().default("member"),
    // Camp-scoped member reference code, e.g. `MAH-M017` — a stable identifier a
    // camp quotes for its OWN off-platform EFT reconciliation (camper → camp's
    // bank account). NOT an AfrikaBurn payment; the platform never moves money.
    // Nullable: org/god memberships carry none. Unique per group.
    refCode: text("ref_code"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (m) => ({
    userGroupUniq: uniqueIndex("memberships_user_group_idx").on(
      m.userId,
      m.groupId,
    ),
    groupIdx: index("memberships_group_idx").on(m.groupId),
    groupRefCodeUniq: uniqueIndex("memberships_group_ref_code_idx").on(
      m.groupId,
      m.refCode,
    ),
  }),
);

// --- Invites -------------------------------------------------------------
// One-time links. `kind` = member | lead_transfer.

export const invites = pgTable(
  "invites",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    token: text("token").notNull().unique(),
    kind: inviteKindEnum("kind").notNull().default("member"),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    expiresAt: timestamp("expires_at", { mode: "date" }),
    usedByUserId: uuid("used_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    usedAt: timestamp("used_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (i) => ({
    groupIdx: index("invites_group_idx").on(i.groupId),
  }),
);

// --- Registrations -------------------------------------------------------
// group × edition, seven-state workflow. Typed columns for the six sections
// (Finlay's field list, docs/sources/scope-theme-camp-registration.txt). A
// camp is "registered" for an edition IFF an `approved` row exists — the
// `isRegistered` predicate in @quagga/core, from which entitlements derive.
// `completed_sections` records which of the six the wizard has finished; the
// submit-gate (all six complete) lives in @quagga/core.

export const registrations = pgTable(
  "registrations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    status: registrationStatusEnum("status").notNull().default("draft"),

    // Section 1 — Identity & contact (camp name/description live on `groups`).
    s1ContactEmail: text("s1_contact_email"),
    s1AltContactName: text("s1_alt_contact_name"),
    s1AltContactPhone: text("s1_alt_contact_phone"),
    s1AltContactEmail: text("s1_alt_contact_email"),

    // Section 2 — Leave No Trace (incl. LNT lead contact).
    s2LntPlan: text("s2_lnt_plan"),
    s2LntLeadName: text("s2_lnt_lead_name"),
    s2LntLeadPhone: text("s2_lnt_lead_phone"),
    s2LntLeadEmail: text("s2_lnt_lead_email"),

    // Section 3 — Participation & gifting.
    s3ParticipationPlan: text("s3_participation_plan"),
    s3OperatingHours: jsonb("s3_operating_hours")
      .$type<string[]>()
      .notNull()
      .default([]),
    s3ScheduleDetail: text("s3_schedule_detail"),
    s3GiftingFood: boolean("s3_gifting_food"),

    // Section 4 — Size & logistics (layout uploads, max 4 — enforced in core).
    s4ExpectedPopulation: integer("s4_expected_population"),
    s4FirstArrivalDate: date("s4_first_arrival_date", { mode: "string" }),
    s4WorkAccessPasses: integer("s4_work_access_passes"),
    s4AreaDimensions: text("s4_area_dimensions"),
    s4LayoutUploadUrls: jsonb("s4_layout_upload_urls")
      .$type<string[]>()
      .notNull()
      .default([]),

    // Section 5 — Sound & placement preferences.
    s5AmplifiedMusic: text("s5_amplified_music"),
    s5SoundPlan: text("s5_sound_plan"),
    s5PlacementFirstChoice: text("s5_placement_first_choice"),
    s5PlacementSecondChoice: text("s5_placement_second_choice"),
    s5NeighbourRequest: text("s5_neighbour_request"),
    s5FamilyFriendly: text("s5_family_friendly"),

    // Section 6 — Suppliers & commerce (structured picker via
    // `supplier_declarations`; this note is free-text overflow).
    s6SuppliersNote: text("s6_suppliers_note"),
    s6PaidPerformers: boolean("s6_paid_performers"),
    s6FeeStructure: text("s6_fee_structure"),
    s6ExpectedBudgetZar: integer("s6_expected_budget_zar"),
    s6PlugAndPlayAck: boolean("s6_plug_and_play_ack"),

    // Which of the six sections the wizard has marked complete.
    completedSections: jsonb("completed_sections")
      .$type<string[]>()
      .notNull()
      .default([]),

    submittedAt: timestamp("submitted_at", { mode: "date" }),
    decidedAt: timestamp("decided_at", { mode: "date" }),
    decidedByUserId: uuid("decided_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (r) => ({
    groupEditionUniq: uniqueIndex("registrations_group_edition_idx").on(
      r.groupId,
      r.editionId,
    ),
    editionStatusIdx: index("registrations_edition_status_idx").on(
      r.editionId,
      r.status,
    ),
  }),
);

// --- Section reviews -----------------------------------------------------
// Per-section AB feedback with open/resolved state.

export const sectionReviews = pgTable(
  "section_reviews",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    registrationId: uuid("registration_id")
      .notNull()
      .references(() => registrations.id, { onDelete: "cascade" }),
    sectionKey: sectionKeyEnum("section_key").notNull(),
    status: sectionReviewStatusEnum("status").notNull().default("open"),
    comment: text("comment").notNull(),
    reviewerId: uuid("reviewer_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sr) => ({
    registrationIdx: index("section_reviews_registration_idx").on(
      sr.registrationId,
    ),
  }),
);

// --- Questionnaire spine (ported 1:1 from Camp 404) ----------------------
// The Burner Bio dispatches through this; `required_actions` is the generic
// "what blocks this user" gate that routes onboarding.

export const questionnaireDefinitions = pgTable("questionnaire_definitions", {
  key: text("key").primaryKey(),
  title: text("title").notNull(),
  definition: jsonb("definition").$type<Questionnaire>().notNull(),
  status: questionnaireStatusEnum("status").notNull().default("draft"),
  version: text("version"),
  createdByUserId: uuid("created_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
});

export const questionnaireActivations = pgTable(
  "questionnaire_activations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    questionnaireKey: text("questionnaire_key").notNull(),
    version: text("version").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    scope: questionnaireScopeEnum("scope").notNull().default("everyone"),
    blocking: boolean("blocking").notNull().default(true),
    status: activationStatusEnum("status").notNull().default("draft"),
    dueAt: timestamp("due_at", { mode: "date" }),
    activatedByUserId: uuid("activated_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    openedAt: timestamp("opened_at", { mode: "date" }),
    closedAt: timestamp("closed_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (a) => ({
    keyIdx: index("questionnaire_activations_key_idx").on(a.questionnaireKey),
    statusIdx: index("questionnaire_activations_status_idx").on(a.status),
  }),
);

export const questionnaireResponses = pgTable(
  "questionnaire_responses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    definitionKey: text("definition_key").notNull(),
    definitionVersion: text("definition_version").notNull(),
    responses: jsonb("responses")
      .$type<QuestionnaireResponses>()
      .notNull()
      .default({}),
    activationId: uuid("activation_id").references(
      () => questionnaireActivations.id,
      { onDelete: "set null" },
    ),
    completedAt: timestamp("completed_at", { mode: "date" }),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (r) => ({
    userDefIdx: uniqueIndex("questionnaire_responses_user_def_idx").on(
      r.userId,
      r.definitionKey,
    ),
    defIdx: index("questionnaire_responses_def_idx").on(r.definitionKey),
  }),
);

export const requiredActions = pgTable(
  "required_actions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: requiredActionTypeEnum("type").notNull(),
    actionKey: text("action_key").notNull(),
    version: text("version"),
    activationId: uuid("activation_id").references(
      () => questionnaireActivations.id,
      { onDelete: "set null" },
    ),
    title: text("title").notNull(),
    blocking: boolean("blocking").notNull().default(true),
    status: requiredActionStatusEnum("status").notNull().default("pending"),
    dueAt: timestamp("due_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { mode: "date" }),
  },
  (ra) => ({
    userActionIdx: uniqueIndex("required_actions_user_action_idx").on(
      ra.userId,
      ra.actionKey,
    ),
    userStatusIdx: index("required_actions_user_status_idx").on(
      ra.userId,
      ra.status,
    ),
  }),
);

// --- Suppliers -----------------------------------------------------------
// Imported from AfrikaBurn's public Suppliers List (source `ab_sheet`) or
// hand-added (`manual`). Vetting status is editable in the org app.

export const suppliers = pgTable(
  "suppliers",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: text("name").notNull(),
    services: text("services"),
    contact: text("contact"),
    website: text("website"),
    vettingStatus: vettingStatusEnum("vetting_status")
      .notNull()
      .default("listed"),
    source: supplierSourceEnum("source").notNull().default("manual"),
    importedAt: timestamp("imported_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (s) => ({
    nameIdx: index("suppliers_name_idx").on(s.name),
    vettingIdx: index("suppliers_vetting_idx").on(s.vettingStatus),
  }),
);

// --- Supplier declarations -----------------------------------------------
// registration × supplier — the structured Section 6 picker (replaces the
// free-text suppliers field).

export const supplierDeclarations = pgTable(
  "supplier_declarations",
  {
    registrationId: uuid("registration_id")
      .notNull()
      .references(() => registrations.id, { onDelete: "cascade" }),
    supplierId: uuid("supplier_id")
      .notNull()
      .references(() => suppliers.id, { onDelete: "cascade" }),
    note: text("note"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sd) => ({
    pk: primaryKey({ columns: [sd.registrationId, sd.supplierId] }),
    supplierIdx: index("supplier_declarations_supplier_idx").on(sd.supplierId),
  }),
);

// --- Payments ------------------------------------------------------------
// Payment DETAILS + reference + status only. No processing, ever. Polymorphic
// subject by string key (`subject_type` + `subject_id`). `reference` is
// human-readable, e.g. QP-2027-MAH-001 (generator in @quagga/core).

export const payments = pgTable(
  "payments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    subjectType: text("subject_type").notNull(),
    subjectId: uuid("subject_id").notNull(),
    amountCents: integer("amount_cents"),
    currency: text("currency").notNull().default("ZAR"),
    reference: text("reference").notNull().unique(),
    status: paymentStatusEnum("status").notNull().default("pending"),
    details: jsonb("details").$type<Record<string, unknown>>(),
    recordedByUserId: uuid("recorded_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (p) => ({
    subjectIdx: index("payments_subject_idx").on(p.subjectType, p.subjectId),
    statusIdx: index("payments_status_idx").on(p.status),
  }),
);

// --- Audit events --------------------------------------------------------
// Written on: elevation, approval/rejection, payment reconciliation.

export const auditEvents = pgTable(
  "audit_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    actorId: uuid("actor_id").references(() => users.id, {
      onDelete: "set null",
    }),
    action: text("action").notNull(),
    subject: text("subject"),
    meta: jsonb("meta").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (a) => ({
    actorIdx: index("audit_events_actor_idx").on(a.actorId),
    actionIdx: index("audit_events_action_idx").on(a.action),
  }),
);
