import {
  pgTable,
  pgEnum,
  text,
  uuid,
  timestamp,
  boolean,
  integer,
  jsonb,
  date,
  primaryKey,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import type {
  Questionnaire,
  QuestionnaireResponses,
  AudienceSpec,
  ProjectPermissions,
  CampHistoryEntry,
  SupplierOnboardingSteps,
} from "@quagga/types";

// Quagga Portal schema (AfrikaBurn Contributors App). The R0 core (migrations
// 0000–0008) is frozen per docs/build-spec.md §Schema; later features extend it
// ONLY by adding tables/columns behind a new append-only migration, never by
// altering or regenerating an earlier one (0009 notifications+bulletins,
// 0010 camp categories). Feature/page agents do not touch this file at all.
// This file is the single hand-authored source of truth; everything under
// packages/db/migrations/ is generated by drizzle-kit and never hand-edited.
//
// Authentication/identity lives in Neon Auth (Better Auth). Our `users` table
// joins to it via `auth_user_id` (the upstream Better Auth user id).

// --- Enums ---------------------------------------------------------------
// Each tuple mirrors a Zod enum in @quagga/types (the validation authority);
// this is the storage authority. Keep the two in sync.

export const groupKindEnum = pgEnum("group_kind", [
  "org",
  "theme_camp",
  "artwork",
  "mutant_vehicle",
]);

export const joinabilityEnum = pgEnum("joinability", ["open", "invite_only"]);

// Reserved: visibility is currently DERIVED (registered ⇒ public). This column
// exists so explicit privacy settings can land later without a migration.
export const groupVisibilityEnum = pgEnum("group_visibility", [
  "default",
  "public",
  "members_only",
  "private",
]);

export const membershipRoleEnum = pgEnum("membership_role", [
  "god",
  "org_staff",
  "lead",
  "admin",
  "member",
]);

export const inviteKindEnum = pgEnum("invite_kind", [
  "member",
  "lead_transfer",
]);

// Roles v2 (questionnaire-spec §"Role kinds"). `kind` governs permanence +
// assignment semantics; `color` is a curated palette key (token-mapped, not hex).
export const projectRoleKindEnum = pgEnum("project_role_kind", [
  "captain",
  "baseline",
  "default",
  "custom",
  "officer",
]);

export const roleColorEnum = pgEnum("role_color", [
  "teal",
  "teal_deep",
  "apricot",
  "peach",
  "sage",
  "olive",
  "rust",
  "neutral",
]);

// Officer assignment consent (questionnaire-spec §"Officers are ALSO
// registrations"). Non-officer assignments are always `accepted`.
export const roleAssignmentConsentEnum = pgEnum("role_assignment_consent", [
  "pending",
  "accepted",
  "declined",
]);

export const registrationStatusEnum = pgEnum("registration_status", [
  "draft",
  "submitted",
  "under_review",
  "changes_requested",
  "approved",
  "rejected",
  "withdrawn",
]);

export const sectionKeyEnum = pgEnum("section_key", [
  "identity",
  "lnt",
  "participation",
  "size_logistics",
  "sound_placement",
  "suppliers_commerce",
]);

export const sectionReviewStatusEnum = pgEnum("section_review_status", [
  "open",
  "resolved",
]);

// Supplier model v2 (docs/supplier-spec.md). `vetting_status` + `source` are
// dead; `standing` is the org's single verdict, `supplier_note_kind` types the
// org-internal timeline. Step states are stored as jsonb (not an enum column)
// on `supplier_onboarding`.
export const supplierStandingEnum = pgEnum("supplier_standing", [
  "good",
  "watch",
  "suspended",
  "diligent_first_timer",
  "adapting",
  "absolute_beginner",
]);

// Whether an imported supplier is returning or a newbie (sheet "Returning
// Supplier?" column). Nullable on the row — blank sheet cells carry none.
export const supplierReturningEnum = pgEnum("supplier_returning", [
  "newbie",
  "returning",
]);

export const supplierNoteKindEnum = pgEnum("supplier_note_kind", [
  "infraction",
  "blessing",
  "note",
]);

export const paymentStatusEnum = pgEnum("payment_status", [
  "pending",
  "reconciled",
  "waived",
]);

// Notifications & bulletins (docs/notifications-spec.md, build-spec §Notifications).
// One inbox, two origins: personal event notifications + org `bulletin`
// broadcasts. Kinds mirror the NotificationKind Zod enum in @quagga/types and
// the leading-glyph map in @quagga/ui's NotificationItem — keep all three in
// sync.
export const notificationKindEnum = pgEnum("notification_kind", [
  "registration",
  "wrangler",
  "role",
  "questionnaire",
  "supplier",
  "security",
  "bulletin",
]);

// Questionnaire spine (ported 1:1 from Camp 404's pattern).
export const requiredActionTypeEnum = pgEnum("required_action_type", [
  "questionnaire",
  "acknowledgement",
  "payment",
  "profile_update",
]);

export const requiredActionStatusEnum = pgEnum("required_action_status", [
  "pending",
  "completed",
  "waived",
  "expired",
]);

export const questionnaireScopeEnum = pgEnum("questionnaire_scope", [
  "everyone",
  "individual",
  "opt_in",
]);

export const activationStatusEnum = pgEnum("activation_status", [
  "draft",
  "open",
  "closed",
]);

export const questionnaireStatusEnum = pgEnum("questionnaire_status", [
  "draft",
  "published",
  "unpublished",
]);

// Where an activation was authored — the hard boundary results never cross.
// `org` = Organiser Console (org_staff/god); `group` = a project's dashboard.
export const questionnaireAuthoredScopeEnum = pgEnum(
  "questionnaire_authored_scope",
  ["org", "group"],
);

// --- Users ---------------------------------------------------------------
// Camp-specific identity join. Minimal by design: NO role columns — every role
// is a `memberships` row. Account persists; per-edition data hangs elsewhere.

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  authUserId: text("auth_user_id").notNull().unique(),
  email: text("email"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Editions ------------------------------------------------------------
// Years are the root namespace. Bios and registrations hang off an edition.
// Seed: AfrikaBurn 2027 (2027-04-26 → 2027-05-02, active).

export const editions = pgTable("editions", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  year: integer("year").notNull().unique(),
  startDate: date("start_date", { mode: "string" }).notNull(),
  endDate: date("end_date", { mode: "string" }).notNull(),
  isActive: boolean("is_active").notNull().default(false),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Burner bios ---------------------------------------------------------
// One row per user × edition (carried forward year to year by confirm-and-copy,
// wave 2+). Field set mirrored from Camp 404's burner profile. `privacy_flags`
// is a per-field public/private map; the HARD-LOCKED always-private fields
// (id_number, passport_number, phone, both emergency contacts, medical) can
// NEVER be set public — enforced in @quagga/core (privacy hard-lock). SA ID /
// passport are pgcrypto-encrypted (never stored plaintext); encryption happens
// in route handlers via @quagga/db/crypto. `attended_years` is the set of
// specific AfrikaBurn years attended (2007–2026, never 2020/2021).

export const burnerBios = pgTable(
  "burner_bios",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),

    // Public-toggleable identity fields.
    displayName: text("display_name"),
    legalName: text("legal_name"),
    homeCity: text("home_city"),
    bio: text("bio"),
    skills: jsonb("skills").$type<string[]>().notNull().default([]),
    // Specific AfrikaBurn years attended (2007–2026, never 2020/2021 — no burn).
    attendedYears: jsonb("attended_years")
      .$type<number[]>()
      .notNull()
      .default([]),
    firstTime: boolean("first_time").notNull().default(false),

    // Contact — `email` is display/contact; `phone` is HARD-LOCKED private
    // (stored E.164).
    contactEmail: text("contact_email"),
    phone: text("phone"),

    // HARD-LOCKED private. Two emergency contacts (on-site + off-site), each
    // split into name + phone (E.164). Stored plaintext, like the other
    // contact fields — only id/passport are pgcrypto-encrypted.
    onsiteContactName: text("onsite_contact_name"),
    onsiteContactPhone: text("onsite_contact_phone"),
    offsiteContactName: text("offsite_contact_name"),
    offsiteContactPhone: text("offsite_contact_phone"),
    medicalNotes: text("medical_notes"),

    // HARD-LOCKED private + pgcrypto-encrypted (base64 ciphertext columns).
    saIdEncrypted: text("sa_id_encrypted"),
    passportEncrypted: text("passport_encrypted"),

    // v3 additions (build-spec §"Burner Bio v3 additions"). All nullable, all
    // self-promotional (never hard-locked). `about` is a "for the burns" bio;
    // `camp_history` is a repeatable list of linked/free-text camps; the ranger
    // trio is inquiry-framed interest, not a commitment.
    about: text("about"),
    campHistory: jsonb("camp_history").$type<CampHistoryEntry[]>(),
    volunteeringInterests: jsonb("volunteering_interests").$type<string[]>(),
    rangerTraining: boolean("ranger_training"),
    rangerCurious: boolean("ranger_curious"),
    greenDotTraining: boolean("green_dot_training"),

    // Per-field public/private map, e.g. { "displayName": true, "bio": true }.
    // Hard-locked fields are force-private regardless of what's stored here.
    privacyFlags: jsonb("privacy_flags")
      .$type<Record<string, boolean>>()
      .notNull()
      .default({}),

    // Questionnaire-engine bookkeeping (this is a "code questionnaire").
    version: text("version").notNull(),
    startedAt: timestamp("started_at", { mode: "date" }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { mode: "date" }),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (b) => ({
    userEditionIdx: uniqueIndex("burner_bios_user_edition_idx").on(
      b.userId,
      b.editionId,
    ),
    editionIdx: index("burner_bios_edition_idx").on(b.editionId),
  }),
);

// --- Profile keys --------------------------------------------------------
// Server-generated keypair at onboarding (reproducible; users never manage
// keys). Used for nothing yet except future QR attestations. The private key is
// stored encrypted; the public key is plaintext.

export const profileKeys = pgTable("profile_keys", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  publicKey: text("public_key").notNull(),
  encryptedPrivateKey: text("encrypted_private_key").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Groups --------------------------------------------------------------
// One joinable-group table. A PROJECT is any non-org group (the kind that
// registers and earns entitlements). Exactly one `org` row is seeded
// ("AfrikaBurn"). `name_normalized` is unique per kind (case/space/punct-
// insensitive; the normalizer lives in @quagga/core).

export const groups = pgTable(
  "groups",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    kind: groupKindEnum("kind").notNull(),
    name: text("name").notNull(),
    nameNormalized: text("name_normalized").notNull(),
    slug: text("slug").notNull(),
    // 60-word limit (for camps) enforced in @quagga/core + the UI.
    description: text("description"),
    joinability: joinabilityEnum("joinability")
      .notNull()
      .default("invite_only"),
    // Reserved column — see groupVisibilityEnum.
    visibility: groupVisibilityEnum("visibility").notNull().default("default"),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (g) => ({
    // Unique per kind, case/space/punct-insensitive (normalized upstream).
    kindNameUniq: uniqueIndex("groups_kind_name_normalized_idx").on(
      g.kind,
      g.nameNormalized,
    ),
    slugUniq: uniqueIndex("groups_slug_idx").on(g.slug),
  }),
);

// --- Memberships ---------------------------------------------------------
// user × group with a role. `god` is only valid on the org group (enforced in
// app logic). unique(user, group).

export const memberships = pgTable(
  "memberships",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    role: membershipRoleEnum("role").notNull().default("member"),
    // Camp-scoped member reference code, e.g. `MAH-M017` — a stable identifier a
    // camp quotes for its OWN off-platform EFT reconciliation (camper → camp's
    // bank account). NOT an AfrikaBurn payment; the platform never moves money.
    // Nullable: org/god memberships carry none. Unique per group.
    refCode: text("ref_code"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (m) => ({
    userGroupUniq: uniqueIndex("memberships_user_group_idx").on(
      m.userId,
      m.groupId,
    ),
    groupIdx: index("memberships_group_idx").on(m.groupId),
    groupRefCodeUniq: uniqueIndex("memberships_group_ref_code_idx").on(
      m.groupId,
      m.refCode,
    ),
  }),
);

// --- Project roles -------------------------------------------------------
// Per-project CUSTOM roles (questionnaire-builder feature) — labels used for
// organisation + questionnaire audiences, distinct from the structural
// `memberships.role` ladder (which governs permissions). Defaults seeded on
// project creation: Captain, Team lead, Burn member. Leads/admins add/rename/
// remove. `name_normalized` is unique per group (case/space/punct-insensitive;
// the normalizer lives in @quagga/core, `normalizeRoleName`).

export const projectRoles = pgTable(
  "project_roles",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    nameNormalized: text("name_normalized").notNull(),
    isDefault: boolean("is_default").notNull().default(false),
    sort: integer("sort").notNull().default(0),
    // Roles v2 (questionnaire-spec §"Roles v2"). `kind` = permanence/assignment
    // class; `color`/`emoji` = display; `permissions` = the privilege OBJECT
    // (keys + config, e.g. manage_questionnaires scope). `officerKey` is the
    // stable org catalog anchor for `officer`-kind rows (null otherwise).
    kind: projectRoleKindEnum("kind").notNull().default("custom"),
    color: roleColorEnum("color").notNull().default("neutral"),
    emoji: text("emoji"),
    permissions: jsonb("permissions")
      .$type<ProjectPermissions>()
      .notNull()
      .default({}),
    officerKey: text("officer_key"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (pr) => ({
    groupNameUniq: uniqueIndex("project_roles_group_name_normalized_idx").on(
      pr.groupId,
      pr.nameNormalized,
    ),
    groupIdx: index("project_roles_group_idx").on(pr.groupId),
  }),
);

// --- Member role assignments ---------------------------------------------
// Many-to-many: a membership may hold multiple custom project roles. Composite
// PK (membership_id × project_role_id) makes each assignment unique.

export const memberRoleAssignments = pgTable(
  "member_role_assignments",
  {
    membershipId: uuid("membership_id")
      .notNull()
      .references(() => memberships.id, { onDelete: "cascade" }),
    projectRoleId: uuid("project_role_id")
      .notNull()
      .references(() => projectRoles.id, { onDelete: "cascade" }),
    // Officer consent (questionnaire-spec §"Officers are ALSO registrations").
    // Non-officer assignments are `accepted` immediately; officer assignments
    // start `pending` and the member must accept. `orgVisible` is set true on an
    // officer's acceptance — the SINGLE explicit channel that shares an
    // officer's contact (name/email/phone) with the org (the bio phone
    // hard-lock stays intact everywhere else).
    consentStatus: roleAssignmentConsentEnum("consent_status")
      .notNull()
      .default("accepted"),
    acceptedAt: timestamp("accepted_at", { mode: "date" }),
    orgVisible: boolean("org_visible").notNull().default(false),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (mra) => ({
    pk: primaryKey({ columns: [mra.membershipId, mra.projectRoleId] }),
    roleIdx: index("member_role_assignments_role_idx").on(mra.projectRoleId),
  }),
);

// --- Invites -------------------------------------------------------------
// One-time links. `kind` = member | lead_transfer.

export const invites = pgTable(
  "invites",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    token: text("token").notNull().unique(),
    kind: inviteKindEnum("kind").notNull().default("member"),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    expiresAt: timestamp("expires_at", { mode: "date" }),
    usedByUserId: uuid("used_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    usedAt: timestamp("used_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (i) => ({
    groupIdx: index("invites_group_idx").on(i.groupId),
  }),
);

// --- Registrations -------------------------------------------------------
// group × edition, seven-state workflow. Typed columns for the six sections
// (Finlay's field list, docs/sources/scope-theme-camp-registration.txt). A
// camp is "registered" for an edition IFF an `approved` row exists — the
// `isRegistered` predicate in @quagga/core, from which entitlements derive.
// `completed_sections` records which of the six the wizard has finished; the
// submit-gate (all six complete) lives in @quagga/core.

export const registrations = pgTable(
  "registrations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    status: registrationStatusEnum("status").notNull().default("draft"),

    // Section 1 — Identity & contact (camp name/description live on `groups`).
    s1ContactEmail: text("s1_contact_email"),
    s1AltContactName: text("s1_alt_contact_name"),
    s1AltContactPhone: text("s1_alt_contact_phone"),
    s1AltContactEmail: text("s1_alt_contact_email"),

    // Section 2 — Leave No Trace (incl. LNT lead contact).
    s2LntPlan: text("s2_lnt_plan"),
    s2LntLeadName: text("s2_lnt_lead_name"),
    s2LntLeadPhone: text("s2_lnt_lead_phone"),
    s2LntLeadEmail: text("s2_lnt_lead_email"),

    // Section 3 — Participation & gifting.
    s3ParticipationPlan: text("s3_participation_plan"),
    s3OperatingHours: jsonb("s3_operating_hours")
      .$type<string[]>()
      .notNull()
      .default([]),
    s3ScheduleDetail: text("s3_schedule_detail"),
    s3GiftingFood: boolean("s3_gifting_food"),

    // Section 4 — Size & logistics (layout uploads, max 4 — enforced in core).
    s4ExpectedPopulation: integer("s4_expected_population"),
    s4FirstArrivalDate: date("s4_first_arrival_date", { mode: "string" }),
    s4WorkAccessPasses: integer("s4_work_access_passes"),
    s4AreaDimensions: text("s4_area_dimensions"),
    s4LayoutUploadUrls: jsonb("s4_layout_upload_urls")
      .$type<string[]>()
      .notNull()
      .default([]),

    // Section 5 — Sound & placement preferences.
    s5AmplifiedMusic: text("s5_amplified_music"),
    s5SoundPlan: text("s5_sound_plan"),
    s5PlacementFirstChoice: text("s5_placement_first_choice"),
    s5PlacementSecondChoice: text("s5_placement_second_choice"),
    s5NeighbourRequest: text("s5_neighbour_request"),
    s5FamilyFriendly: text("s5_family_friendly"),

    // Section 6 — Suppliers & commerce (structured picker via
    // `supplier_declarations`; this note is free-text overflow).
    s6SuppliersNote: text("s6_suppliers_note"),
    s6PaidPerformers: boolean("s6_paid_performers"),
    s6FeeStructure: text("s6_fee_structure"),
    s6ExpectedBudgetZar: integer("s6_expected_budget_zar"),
    s6PlugAndPlayAck: boolean("s6_plug_and_play_ack"),

    // Grant-interest flag (questionnaire-builder feature). Nullable tri-state:
    // null = not asked yet (no MV/art grant flow), true/false once declared.
    // Drives the `mv_grant_requesters` / `art_grant_requesters` audiences.
    grantsInterest: boolean("grants_interest"),

    // Which of the six sections the wizard has marked complete.
    completedSections: jsonb("completed_sections")
      .$type<string[]>()
      .notNull()
      .default([]),

    submittedAt: timestamp("submitted_at", { mode: "date" }),
    decidedAt: timestamp("decided_at", { mode: "date" }),
    decidedByUserId: uuid("decided_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (r) => ({
    groupEditionUniq: uniqueIndex("registrations_group_edition_idx").on(
      r.groupId,
      r.editionId,
    ),
    editionStatusIdx: index("registrations_edition_status_idx").on(
      r.editionId,
      r.status,
    ),
  }),
);

// --- Section reviews -----------------------------------------------------
// Per-section AB feedback with open/resolved state.

export const sectionReviews = pgTable(
  "section_reviews",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    registrationId: uuid("registration_id")
      .notNull()
      .references(() => registrations.id, { onDelete: "cascade" }),
    sectionKey: sectionKeyEnum("section_key").notNull(),
    status: sectionReviewStatusEnum("status").notNull().default("open"),
    comment: text("comment").notNull(),
    reviewerId: uuid("reviewer_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sr) => ({
    registrationIdx: index("section_reviews_registration_idx").on(
      sr.registrationId,
    ),
  }),
);

// --- Questionnaire spine (ported 1:1 from Camp 404) ----------------------
// The Burner Bio dispatches through this; `required_actions` is the generic
// "what blocks this user" gate that routes onboarding.

export const questionnaireDefinitions = pgTable("questionnaire_definitions", {
  key: text("key").primaryKey(),
  title: text("title").notNull(),
  definition: jsonb("definition").$type<Questionnaire>().notNull(),
  status: questionnaireStatusEnum("status").notNull().default("draft"),
  version: text("version"),
  createdByUserId: uuid("created_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
});

export const questionnaireActivations = pgTable(
  "questionnaire_activations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    questionnaireKey: text("questionnaire_key").notNull(),
    version: text("version").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    scope: questionnaireScopeEnum("scope").notNull().default("everyone"),
    blocking: boolean("blocking").notNull().default(true),
    status: activationStatusEnum("status").notNull().default("draft"),
    dueAt: timestamp("due_at", { mode: "date" }),
    // Audience-targeting columns (questionnaire-builder feature). `authoredScope`
    // + `groupId` are the results-visibility boundary; `audience` is the jsonb
    // spec resolved at send time (@quagga/core resolveAudience); `editionId`
    // scopes edition-relative selectors. All nullable so pre-feature rows (the
    // Burner Bio spine) are untouched.
    authoredScope: questionnaireAuthoredScopeEnum("authored_scope")
      .notNull()
      .default("org"),
    groupId: uuid("group_id").references(() => groups.id, {
      onDelete: "cascade",
    }),
    editionId: uuid("edition_id").references(() => editions.id, {
      onDelete: "cascade",
    }),
    audience: jsonb("audience").$type<AudienceSpec>(),
    activatedByUserId: uuid("activated_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    openedAt: timestamp("opened_at", { mode: "date" }),
    closedAt: timestamp("closed_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (a) => ({
    keyIdx: index("questionnaire_activations_key_idx").on(a.questionnaireKey),
    statusIdx: index("questionnaire_activations_status_idx").on(a.status),
    groupIdx: index("questionnaire_activations_group_idx").on(a.groupId),
    editionIdx: index("questionnaire_activations_edition_idx").on(a.editionId),
  }),
);

export const questionnaireResponses = pgTable(
  "questionnaire_responses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    definitionKey: text("definition_key").notNull(),
    definitionVersion: text("definition_version").notNull(),
    responses: jsonb("responses")
      .$type<QuestionnaireResponses>()
      .notNull()
      .default({}),
    activationId: uuid("activation_id").references(
      () => questionnaireActivations.id,
      { onDelete: "set null" },
    ),
    completedAt: timestamp("completed_at", { mode: "date" }),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (r) => ({
    userDefIdx: uniqueIndex("questionnaire_responses_user_def_idx").on(
      r.userId,
      r.definitionKey,
    ),
    defIdx: index("questionnaire_responses_def_idx").on(r.definitionKey),
  }),
);

export const requiredActions = pgTable(
  "required_actions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: requiredActionTypeEnum("type").notNull(),
    actionKey: text("action_key").notNull(),
    version: text("version"),
    activationId: uuid("activation_id").references(
      () => questionnaireActivations.id,
      { onDelete: "set null" },
    ),
    title: text("title").notNull(),
    blocking: boolean("blocking").notNull().default(true),
    status: requiredActionStatusEnum("status").notNull().default("pending"),
    dueAt: timestamp("due_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { mode: "date" }),
  },
  (ra) => ({
    userActionIdx: uniqueIndex("required_actions_user_action_idx").on(
      ra.userId,
      ra.actionKey,
    ),
    userStatusIdx: index("required_actions_user_status_idx").on(
      ra.userId,
      ra.status,
    ),
  }),
);

// --- Suppliers -----------------------------------------------------------
// Supplier model v2 (docs/supplier-spec.md). `source`/`vetting_status` are
// gone; the org sees three things only — did they onboard (derived from
// `supplier_onboarding`), what `standing` are they in, and the notes trail
// (`supplier_notes`). `userId` optionally links a supplier to a burner account
// (matched by email overlap) so a supplier can sign into their own portal.

export const suppliers = pgTable(
  "suppliers",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: text("name").notNull(),
    services: text("services"),
    contact: text("contact"),
    website: text("website"),
    // Normalised category chip ported from the sheet's Category column
    // (Transportation→Transport, FIREWOOD DELIVERY→Firewood Delivery, title-
    // cased; multiple joined with " / "). Nullable — hand-added suppliers may
    // carry none.
    category: text("category"),
    // Returning vs newbie, ported from the sheet's "Returning Supplier?"
    // column. Nullable — blank sheet cells / hand-added rows carry none.
    returning: supplierReturningEnum("returning"),
    // Org-set verdict, visible everywhere (org console + camp-side picker).
    standing: supplierStandingEnum("standing").notNull().default("good"),
    // Optional account link (email overlap). Nullable — most imported rows have
    // no signed-in supplier yet.
    userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }),
    importedAt: timestamp("imported_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (s) => ({
    nameIdx: index("suppliers_name_idx").on(s.name),
    standingIdx: index("suppliers_standing_idx").on(s.standing),
    userIdx: index("suppliers_user_idx").on(s.userId),
  }),
);

// --- Supplier onboarding -------------------------------------------------
// Per supplier × edition onboarding checklist state. The seven steps + their
// completion/confirmation semantics are a code catalog
// (@quagga/core SUPPLIER_ONBOARDING_STEPS); `steps` is the jsonb state map
// (stepKey → status). Progress (n/7) and "onboarded properly" derive in core.

export const supplierOnboarding = pgTable(
  "supplier_onboarding",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    supplierId: uuid("supplier_id")
      .notNull()
      .references(() => suppliers.id, { onDelete: "cascade" }),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    steps: jsonb("steps")
      .$type<SupplierOnboardingSteps>()
      .notNull()
      .default({}),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (so) => ({
    supplierEditionUniq: uniqueIndex("supplier_onboarding_supplier_edition_idx").on(
      so.supplierId,
      so.editionId,
    ),
    editionIdx: index("supplier_onboarding_edition_idx").on(so.editionId),
  }),
);

// --- Supplier notes ------------------------------------------------------
// Org-internal timeline about a supplier (infraction / blessing / note). Never
// visible to the supplier or to camps. POPIA-relevant — audit-logged upstream.

export const supplierNotes = pgTable(
  "supplier_notes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    supplierId: uuid("supplier_id")
      .notNull()
      .references(() => suppliers.id, { onDelete: "cascade" }),
    authorId: uuid("author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    kind: supplierNoteKindEnum("kind").notNull().default("note"),
    body: text("body").notNull(),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sn) => ({
    supplierIdx: index("supplier_notes_supplier_idx").on(sn.supplierId),
  }),
);

// --- Supplier declarations -----------------------------------------------
// registration × supplier — the structured Section 6 picker (replaces the
// free-text suppliers field).

export const supplierDeclarations = pgTable(
  "supplier_declarations",
  {
    registrationId: uuid("registration_id")
      .notNull()
      .references(() => registrations.id, { onDelete: "cascade" }),
    supplierId: uuid("supplier_id")
      .notNull()
      .references(() => suppliers.id, { onDelete: "cascade" }),
    note: text("note"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sd) => ({
    pk: primaryKey({ columns: [sd.registrationId, sd.supplierId] }),
    supplierIdx: index("supplier_declarations_supplier_idx").on(sd.supplierId),
  }),
);

// --- Payments ------------------------------------------------------------
// Payment DETAILS + reference + status only. No processing, ever. Polymorphic
// subject by string key (`subject_type` + `subject_id`). `reference` is
// human-readable, e.g. QP-2027-MAH-001 (generator in @quagga/core).

export const payments = pgTable(
  "payments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    subjectType: text("subject_type").notNull(),
    subjectId: uuid("subject_id").notNull(),
    amountCents: integer("amount_cents"),
    currency: text("currency").notNull().default("ZAR"),
    reference: text("reference").notNull().unique(),
    status: paymentStatusEnum("status").notNull().default("pending"),
    details: jsonb("details").$type<Record<string, unknown>>(),
    recordedByUserId: uuid("recorded_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (p) => ({
    subjectIdx: index("payments_subject_idx").on(p.subjectType, p.subjectId),
    statusIdx: index("payments_status_idx").on(p.status),
  }),
);

// --- Audit events --------------------------------------------------------
// Written on: elevation, approval/rejection, payment reconciliation.

export const auditEvents = pgTable(
  "audit_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    actorId: uuid("actor_id").references(() => users.id, {
      onDelete: "set null",
    }),
    action: text("action").notNull(),
    subject: text("subject"),
    meta: jsonb("meta").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (a) => ({
    actorIdx: index("audit_events_actor_idx").on(a.actorId),
    actionIdx: index("audit_events_action_idx").on(a.action),
  }),
);

// --- Bulletins -----------------------------------------------------------
// Org-authored broadcast to an AUDIENCE (reuses the questionnaire audience
// machinery verbatim — `audience` is the same jsonb AudienceSpec as
// `questionnaire_activations.audience`; resolution is @quagga/core
// `resolveAudience`, one resolver, two consumers). A bulletin is a draft until
// `published_at` is stamped; publishing fans out one `notifications` row (kind
// `bulletin`) per resolved recipient. Also a standalone deep-linkable page.
// Informational only — bulletins never collect data (fewer-forms law).

export const bulletins = pgTable(
  "bulletins",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    bodyMd: text("body_md").notNull(),
    // Same enum/shape as questionnaire audiences (validated by AudienceSpec in
    // @quagga/types; resolved by @quagga/core resolveAudience at publish time).
    audience: jsonb("audience").$type<AudienceSpec>().notNull(),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    // Null = draft; set on publish (the fan-out trigger).
    publishedAt: timestamp("published_at", { mode: "date" }),
    pinned: boolean("pinned").notNull().default(false),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (b) => ({
    editionIdx: index("bulletins_edition_idx").on(b.editionId),
    publishedIdx: index("bulletins_published_idx").on(b.publishedAt),
  }),
);

// --- Camp categories -----------------------------------------------------
// Org-defined per-edition "theme topics" taxonomy (build-spec §"Camp
// categories"). The org CRUDs the catalog per edition (label, optional emoji,
// sort); camps pick ≥0 via `group_categories`. `label_normalized` (the
// @quagga/core `normalizeCategoryLabel`) is unique per edition — dedupe is
// case/space/punct-insensitive, mirroring the groups name-dedupe pattern.

export const campCategories = pgTable(
  "camp_categories",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    labelNormalized: text("label_normalized").notNull(),
    // Optional display emoji (curated by the org — free text, single glyph).
    emoji: text("emoji"),
    sort: integer("sort").notNull().default(0),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (c) => ({
    editionLabelUniq: uniqueIndex("camp_categories_edition_label_idx").on(
      c.editionId,
      c.labelNormalized,
    ),
    editionSortIdx: index("camp_categories_edition_sort_idx").on(
      c.editionId,
      c.sort,
    ),
  }),
);

// --- Group ↔ category join -----------------------------------------------
// Many-to-many: a group (camp/project) picks zero or more categories from its
// edition's catalog. Composite PK makes each pick unique; the reverse index
// powers per-category usage counts + the directory filter. The category's
// edition scope is enforced in @quagga/core / the store (a group may only pick
// from its active edition's catalog).

export const groupCategories = pgTable(
  "group_categories",
  {
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => campCategories.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (gc) => ({
    pk: primaryKey({ columns: [gc.groupId, gc.categoryId] }),
    categoryIdx: index("group_categories_category_idx").on(gc.categoryId),
  }),
);

// --- Notifications -------------------------------------------------------
// Per-account inbox. Append-only; `read_at` set on open ("mark all read" bulk-
// sets it). Generated by EXISTING events (registration decisions, wrangler
// assignment, role/officer acceptance, questionnaire release, supplier org-
// confirmations, security events) + bulletin fan-out. `bulletin_id` links a
// `bulletin`-kind row back to its source. NO new PII — previews never carry
// hard-locked fields (enforced by the @quagga/core payload builders).

export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    kind: notificationKindEnum("kind").notNull(),
    title: text("title").notNull(),
    body: text("body"),
    link: text("link"),
    bulletinId: uuid("bulletin_id").references(() => bulletins.id, {
      onDelete: "cascade",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    readAt: timestamp("read_at", { mode: "date" }),
  },
  (n) => ({
    // Unread count + filter: (user, read_at).
    userReadIdx: index("notifications_user_read_idx").on(n.userId, n.readAt),
    // Inbox list, newest first: (user, created_at desc).
    userCreatedIdx: index("notifications_user_created_idx").on(
      n.userId,
      n.createdAt.desc(),
    ),
  }),
);
