// Real excerpt from AfrikaBurn's public Suppliers List Google Sheet
// (https://docs.google.com/spreadsheets/d/1XU2gAt5E9GczVHZWpcD0_CsEeE--iX9aWmnWd19bgMI),
// fetched via its CSV export, kept verbatim as parser test fixture. Personal
// cell-phone numbers and postal addresses appear in the RAW sheet (this is
// what parseSuppliersCsv must scrub) — nothing here is written back out;
// the parser's own privacy tests assert none of it survives parsing.
export const AB_SUPPLIERS_SAMPLE_CSV = `"Supplier Name","Contact","Status","Category","Returning Supplier?","ALL SUPPLIER RELATED FEES AND CREW PASSES
PURCHASED FOR AB2025?","","Notes","SUPPLIER REGISTRATION 
COMPLETE FOR AB2025?","",""
"Dimensions Bedouin Stretch Tent Hire (Pty) Ltd","Heather Dreyer","In Good Standing","Stretch Tents","Yes","Refundable deposit paid","TRUE","","","",""
"","+27833538376","","","","Supplier contract signed","TRUE","","","",""
"","+27215101043","","","","Inventory log submitted","TRUE","","","",""
"","heather@dimensionstents.com","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"BedouinTent Masterz","Patrick Muchemwa","","Stretch Tents","Yes","Refundable deposit paid","TRUE","","","",""
"","+27813408223","","","","Supplier contract signed","TRUE","","","",""
"","info@bedouintentmasterz.com","","","","Inventory log submitted","FALSE","","","",""
"","","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"Jenquan Logistics","Quan Roberts","In Good Standing","Transportation","Yes","Refundable deposit paid","TRUE","","","",""
"","0741680175  ","","","","Supplier contract signed","TRUE","","","",""
"","jenquanlogistics@outlook.com","","","","Inventory log submitted","FALSE","","","",""
"","","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"Day Star stretch tents","Michael","Able & Willing To Adapt","Stretch Tents","Yes","Refundable deposit paid","TRUE","","","",""
"","+27735541890","","","","Supplier contract signed","TRUE","","","",""
"","daystarstrechtents@gmail.com","","","","Inventory log submitted","FALSE","","","",""
"","","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"Cairo Stretch Tents","Yusufu Musa","In Good Standing","Stretch Tents","Yes","Refundable deposit paid","TRUE","","","",""
"","+27823578493","","","","Supplier contract signed","TRUE","","","",""
"","cairostretchtents@gmail.com","","","","Inventory log submitted","FALSE","","","",""
"","","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"Axis event solutions","Shawn Visser","In Good Standing","Stretch Tents","Yes","Refundable deposit paid","TRUE","","","",""
"","+27738986367","","","","Supplier contract signed","TRUE","","","",""
"","tents@axisevents.co.za","","","","Inventory log submitted","FALSE","","","",""
"","","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"Expo Connection","Peter Sydow","In Good Standing","Generators/Power Supply","Yes","Refundable deposit paid","FALSE","","","",""
"","+27723081011","","","","Supplier contract signed","TRUE","","","",""
"","+27215563079","","","","Inventory log submitted","FALSE","","","",""
"","peter@expoconnection.co.za","","","","Supplier Registration Fee paid","FALSE","","",""," "
"Deharn Stretch Tents","Lenny","In Good Standing","Stretch Tents","Yes","Refundable deposit paid","TRUE","","","",""
"","+27634189911","","","","Supplier contract signed","TRUE","","","",""
"","deharnstretchtents85@gmail.com","","","","Inventory log submitted","FALSE","","","",""
"","","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","TRUE","","","",""
"Poswa Logistics and Services","Zizipho Gcasamba","Diligent First Timer","Transport ","Newbie","Refundable deposit paid","FALSE","","","",""
"","+27607077011","","","","Supplier contract signed","TRUE","","","",""
"","z.gcasamba@gmail.com","","","","Inventory log submitted","FALSE","","","",""
"","","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"Godfrey Family Farms","Horatio Godfrey","Diligent First Timer","FIREWOOD DELIVERY","Newbie","Refundable deposit paid","FALSE","Tankwa local farmer","","",""
"","+27 0737734336","","Transport ","","Supplier contract signed","TRUE","","","",""
"","+ 27 0835507119","","","","Inventory log submitted","FALSE","","","",""
"","horatiogodfrey1@gmail.com","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"Classic Cape Stretch Tents","Tatenda (Saint)","Diligent First Timer","Stretch Tents","Newbie","Refundable deposit paid","TRUE","","","",""
"","+27678682336","","","","Supplier contract signed","TRUE","","","",""
"","classiccapestretchtents@gmail.com","","","","Inventory log submitted","FALSE","","","",""
"","","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"SLAVE DISTRIBUTORS CC","MARCEL ZANDBERG","In Good Standing","Sound & Lighting","Yes","Refundable deposit paid","TRUE","","","",""
"","+27834086953","","","","Supplier contract signed","TRUE","","","",""
"","info@slavedistributors.com","","","","Inventory log submitted","FALSE","","","",""
"","","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"Easy Magnificent Tents","Stanley Mutikani","Diligent First Timer","Stretch Tents","Newbie","Refundable deposit paid","TRUE","","","",""
"","+27815425292","","","","Supplier contract signed","TRUE","","","",""
"","+27620149949","","","","Inventory log submitted","FALSE","","","",""
"","stanlymutikani@gmail.com","","","","Supplier Registration Fee paid","FALSE","","","",""
"","","","","","Crew passes purchased","FALSE","","","",""
"Tentex Stretch Tents","Terrance Jakopo","In Good Standing","Stretch Tents","Yes","","","","","",""
"","+27747624911","","","","","","","","",""
"","tentexstretchtents@yahoo.com","","","","","","","","",""
"Aurras Group (Pty) Ltd","Oscar Arnott","In Good Standing","Sound & Lighting","Yes","","","","","",""
"","+27737029090","","Generators/Power Supply","","","","","","",""
"","+27215553959","","","","","","","","",""
"","Oscar@aurrasgroup.co.za","","","","","","","","",""
"","justin@aurrasgroup.co.za","","","","","","","","",""
"DOS Tents pty ltd","Dean Farham","Diligent First Timer","Stretch Tents","Newbie","","","","","",""
"","+27795695564","","","","","","","","",""
"","dean@dostents.co.za","","","","","","","","",""
"Chariots Transport","Frans van Kraaienburg","In Good Standing","Transport ","Yes","","","Transporting of:","","",""
"","fransvk@me.com","","","","","","Mutant vehicles","","",""
"","+27723246422","","","","","","Containers","","",""
"","Plaas Tandskoonmaak 1
Tankwa Rural
Ceres
6835","","","","","","Water tanks/water","","",""
"Luyolo Service Provider PTY Ltd","Lofty Baadjies / Lizelle Baadjies","In Good Standing","FIREWOOD DELIVERY","Yes","","","","","",""
"","+27649062782","","","","","","","","",""
"","lizelletitus@gmail.com","","","","","","","","",""
"TENTICKLE STRETCH TENTS","Wesley","Diligent First Timer","Stretch Tents","Newbie","","","","","",""
"","+27722639916","","","","","","","","",""
"","+27215930134","","","","","","","","",""
"","hire@tentickle.co.za","","","","","","","","",""
"GK Transport","George","In Good Standing","Transport ","Yes","","","","","",""
"","+27786883082","","","","","","containers","","",""
"","gkavukutu@gmail.com","","","","","","","","",""`;
